version: '3'
volumes:
   deps:

services:
  mru:
    image: node:14
    working_dir: /usr/src/app
    command: npm run start
    environment:
      PROJECT_NAME: mru
      PROJECT_BUILD: dev
      CHOKIDAR_USEPOLLING: "true"
      TSC_COMPILE_ON_ERROR: "true"
    volumes:
      - .:/usr/src/app
      - deps:/usr/src/app/node_modules
    expose:
      - 3000
