version: '2'
volumes:
  deps:

services:
  mru:
    image: node:13.7
    working_dir: /usr/src/app
    command: npm run server
    environment:
      PROJECT_NAME: mru
      PROJECT_BUILD: dev
      NODE_ENV: development
      WDS_SOCKET_PORT: 8000
      CHOKIDAR_USEPOLLING: "true"
    volumes:
      - .:/usr/src/app
      - deps:/usr/src/app/node_modules
    expose:
      - 8000
  builder:
    image: node:13.7
    working_dir: /usr/src/app
    command: npm run start
    environment:
      PROJECT_NAME: mru
      PROJECT_BUILD: dev
      NODE_ENV: development
      WDS_SOCKET_PORT: 8000
      CHOKIDAR_USEPOLLING: "true"
    volumes:
      - .:/usr/src/app
      - deps:/usr/src/app/node_modules
    expose:
      - 8000
