export const CHECKLIST_ITEM_TOGGLE='CHECKLIST_ITEM_TOGGLE';
export const CHECKLIST_ITEM_UPDATE='CHECKLIST_ITEM_UPDATE';
export const CHECKLIST_ITEM_ADD='CHECKLIST_ITEM_ADD';
export const CHECKLIST_ITEM_CHECK='CHECKLIST_ITEM_CHECK';

export const CHECKLIST_SELECT='CHECKLIST_SELECT';
export const CHECKLIST_UPDATE='CHECKLIST_UPDATE';
export const CHECKLIST_ADD='CHECKLIST_ADD';
export const CHECKLIST_DELETE='CHECKLIST_DELETE';
