version: '2'
volumes:
  deps:
    driver: local

services:
  mru:
    image: node:13.7.0
    working_dir: /usr/src/app
    command: make serve
    environment:
      PROJECT_NAME: mru-ui
      PROJECT_BUILD: dev
      NODE_ENV: debug
    volumes:
      - .:/usr/src/app
      - deps:/usr/src/app/node_modules
    expose:
      - 3000
